### ISSUE TITLE
Error when trying to access the metrics in browser

### ISSUE THREAD

**Issue by kritag** [Pelleplutt/tibber-exporter#7]
2021-05-16 12:51:06 INFO     Collect
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/exposition.py", line 123, in prometheus_app
    status, header, output = _bake_output(registry, accept_header, params)
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/exposition.py", line 105, in _bake_output
    output = encoder(registry)
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/exposition.py", line 177, in generate_latest
    for metric in registry.collect():
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/registry.py", line 83, in collect
    for metric in collector.collect():
  File "/app/tibber-exporter.py", line 319, in collect
    self.add_metrics_live_measurement(metrics, home, live_measurement)
  File "/app/tibber-exporter.py", line 283, in add_metrics_live_measurement
    metrics['current'].add_metric([home.id, home.get_name(), '2'], float(data['currentL2']))
TypeError: float() argument must be a string or a number, not 'NoneType'

Browser shows:
A server error occurred.  Please contact the administrator.

**Comment by SagenKoder** [comment]
I got the same error and don't really know Python. Maybe the API has changed?
I would really like this to work so any suggestions? Any activity here?

**Comment by Pelleplutt** [comment]
Hi Both, sorry for my late response. I think @SagenKoder is right here in the PR he submitted. This was a scenario I was yet to see in my subscription and I had not handled the lack of metrics for some of the phases from tibber. I merged #23, let me know if the error persists after that and I will have another look.
